import React from "react"
import Head from "next/head"
import { RoomChats } from "../../components"

export default function Room () {
    return(
        <main>
            <Head>
                <title>Discord | Sala</title>
                <meta name="desciption" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <RoomChats />
        </main>
    )
}