import Head from 'next/head'
import { Directs } from '../components'
import styles from '../styles/Home.module.scss'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainContainer}>
        <Directs />
      </main>
    </div>
  )
}
